# Generated by Django 6.0.1 on 2026-02-13 23:47

import django.core.validators
import django.db.models.deletion
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Endereço')),
                ('business_hours_weekdays', models.CharField(default='09:00 - 18:00', max_length=100, verbose_name='Horário (Segunda a Sexta)')),
                ('business_hours_saturday', models.CharField(default='09:00 - 13:00', max_length=100, verbose_name='Horário (Sábado)')),
                ('business_hours_sunday', models.CharField(default='Fechado', max_length=100, verbose_name='Horário (Domingo)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Contato do site',
                'verbose_name_plural': 'Contato do site',
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='properties/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg']), properties.models.validate_video_size], verbose_name='Vídeo')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Vídeo do imóvel',
                'verbose_name_plural': 'Vídeos do imóvel',
                'ordering': ['order', 'id'],
            },
        ),
    ]
