# Generated by Django 6.0.1 on 2026-02-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_sitecontact_propertyvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontact',
            name='brand_message',
            field=models.TextField(blank=True, default='', verbose_name='Mensagem institucional'),
        ),
    ]
