# Generated by Django 6.0.1 on 2026-02-14 00:06

from django.db import migrations


def backfill_main_image_gallery(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    PropertyImage = apps.get_model('properties', 'PropertyImage')

    for property_obj in Property.objects.exclude(main_image=''):
        has_gallery = PropertyImage.objects.filter(property_id=property_obj.id).exists()
        if has_gallery:
            continue

        PropertyImage.objects.create(
            property_id=property_obj.id,
            image=property_obj.main_image,
            caption='Imagem principal',
            order=0,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_sitecontact_brand_message'),
    ]

    operations = [
        migrations.RunPython(backfill_main_image_gallery, migrations.RunPython.noop),
    ]
