# Generated by Django 6.0.1 on 2026-02-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_backfill_main_image_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontact',
            name='hero_subtitle',
            field=models.TextField(default='Da primeira visita a assinatura, conduzimos todo o processo com estrategia comercial e atencao aos detalhes.', verbose_name='Subtítulo principal da Home'),
        ),
        migrations.AddField(
            model_name='sitecontact',
            name='hero_title',
            field=models.TextField(default='Imoveis de alto impacto para compras inteligentes.', verbose_name='Título principal da Home'),
        ),
        migrations.AddField(
            model_name='sitecontact',
            name='site_name',
            field=models.CharField(default='Abritta Prime', max_length=120, verbose_name='Nome da aplicação'),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='brand_message',
            field=models.TextField(blank=True, default='Curadoria imobiliaria premium para quem busca decisao segura, negociacao inteligente e atendimento consultivo.', verbose_name='Mensagem institucional'),
        ),
    ]
